### ISSUE TITLE
v4.0.0-beta.5. Crunchyroll. Crash 

### ISSUE THREAD

**Issue by IIeTp** [vitalygashkov/streamyx#130]
Скину серию логов о том как крашатся кранчи
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

SocketError: other side closed
    at TLSSocket.<anonymous> (C:\snapshot\streamyx\node_modules\undici\lib\dispatcher\client-h1.js:681:24)
    at TLSSocket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UND_ERR_SOCKET',
  socket: {
    localAddress: '192.168.1.25',
    localPort: 13443,
    remoteAddress: '86.57.191.16',
    remotePort: 443,
    remoteFamily: 'IPv4',
    timeout: undefined,
    bytesWritten: 19422,
    bytesRead: 79645082
  }
}
```
[202404220130_15744.log](https://github.com/vitalygashkov/streamyx/files/15060697/202404220130_15744.log)

**Comment by vitalygashkov** [comment]
Проблема воспроизводится в 11-й бете?

https://github.com/vitalygashkov/streamyx/releases/tag/v4.0.0-beta.11

**Comment by IIeTp** [comment]
повторю с новой бетой и дополню

**Comment by IIeTp** [comment]
beta 11, такая ошибка была и раньше
```
2024-4-23 11:46:33 INFO   One Piece ∙ S8 ∙ E588 ∙ Meeting Again After Two Years! Luffy and Law!
undefined:1
{"status":"OK","license":"CAISggMKTgogN0NENUMzMTg0Qjk5MThBNDAxMDAwMDAwMDAwMDAwMDASJgoQubFrzb/bSlyENOXWt/nAihABMhA6VmJ0Nfyg/h/6+aO8TxPwIAEoABIlCAEQARgAIIDGCiiAxgowgIwVOABCAEgAUABYAGABcAB4AYABABpmEhD4UEySYAcB9C0dBJhoB4L7GlAq0GAU6N79WMZ1r4wUIYelYoXUG6LByyHourTzjRzLb6S8X2AiR6Sc1jE1hxZtOj8zZeaWLWapCWGLJ9MVGR5hsRxoJeYMjlzSz3HuGL3NaCABGpgBChDTnr5PjH84j7K+RYqabcylEhBQbhwYk3ToVf02u7CPBNWmGiDXEV/enookXeYIXCa/PVa+0MywSFhrcxVhHlFW1CIUbCACKAEyCAgAECoYACAAOggIABAqG

SyntaxError: Unterminated string in JSON at position 455
    at JSON.parse (<anonymous>)
    at Cdm.responseDataFilter [as _responseDataFilter] (C:\snapshot\streamyx\dist\src\drm.js:23:33)
    at IncomingMessage.<anonymous> (C:\snapshot\streamyx\packages\wive\dist\wive.js)
    at IncomingMessage.emit (node:events:518:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at flow (node:internal/streams/readable:1281:53)
    at resume_ (node:internal/streams/readable:1260:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.11.1
```
[202404230823_4416.log](https://github.com/vitalygashkov/streamyx/files/15074103/202404230823_4416.log)

**Comment by vitalygashkov** [comment]
> SyntaxError: Unterminated string in JSON at position 455

Выглядит, будто от самого Crunchyroll приходит некорректный JSON в ответе на запрос. В 12-й бете добавил обработку этой ошибки и инфу для отладки. Когда повторится - нужно будет снова скинуть сюда лог-файл.
