### ISSUE TITLE
v3.6.26 error

### ISSUE THREAD

**Issue by girod2033** [vitalygashkov/streamyx#41]
Hello.

`pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module 'jsrsasign'
Require stack:
- C:\snapshot\streamyx\dist\packages\widevinejs\lib\utils\crypto.js
- C:\snapshot\streamyx\dist\packages\widevinejs\lib\cdm\cmac.js
- C:\snapshot\streamyx\dist\packages\widevinejs\lib\cdm\session.js
- C:\snapshot\streamyx\dist\packages\widevinejs\lib\cdm\cdm.js
- C:\snapshot\streamyx\dist\packages\widevinejs\lib\cdm\index.js
- C:\snapshot\streamyx\dist\packages\widevinejs\widevinejs.js
- C:\snapshot\streamyx\dist\src\drm.js
- C:\snapshot\streamyx\dist\streamyx.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\snapshot\streamyx\dist\packages\widevinejs\lib\utils\crypto.js:5:21)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\lib\\utils\\crypto.js',
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\lib\\cdm\\cmac.js',
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\lib\\cdm\\session.js',
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\lib\\cdm\\cdm.js',
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\lib\\cdm\\index.js',
    'C:\\snapshot\\streamyx\\dist\\packages\\widevinejs\\widevinejs.js',
    'C:\\snapshot\\streamyx\\dist\\src\\drm.js',
    'C:\\snapshot\\streamyx\\dist\\streamyx.js'
  ],
  pkg: true
}

Node.js v18.5.0`

**Comment by vitalygashkov** [comment]
Fixed in #42
