### ISSUE TITLE
Downloading videos from wink

### ISSUE THREAD

**Issue by Roman-tex** [vitalygashkov/streamyx#44]
When trying to download a [video](https://wink.ru/episodes/klassika-na-dvortsovoy-klassika-na-dvortsovoy-2021-year-2021) from "Wink", the error

"/snapshot/streamyx/dist/src/downloader.js:38
                        if (!content Keys.length) {
                                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Downloader.start (/snapshot/streamyx/dist/src/downloader.js:38:34)
    at async start Download (/snapshot/streamyx/dist/streamyx.js:20:5)
    at asyncload Provider (/snapshot/streamyx/dist/streamyx.js:31:13)
    at asyncload Providers (/snapshot/streamyx/dist/streamyx.js:55:13)

Node.js v18.5.0"

<img width="986" alt="text" src="https://github.com/vitalygashkov/streamyx/assets/93786806/ba642850-a50e-4e95-8efd-b07ad12c61b2">

**Comment by Roman-tex** [comment]
Solution: start with a parameter.
But there was a problem with getting the keys for wink)
