### ISSUE TITLE
Crunchyroll. Ошибка загрузки файла.

### ISSUE THREAD

**Issue by IIeTp** [vitalygashkov/streamyx#79]
Тестировалось на разных тайтлах. Первые серии качается нормально, затем, спустя время возникает ошибка и даже скачанные серии повторно не даются скачаться.

`streamyx-win-x64.exe https://www.crunchyroll.com/ru/series/GY49D29ZR/kenka-bancho-otome--girl-beats-boys-`

[202403160530_22848.log](https://github.com/vitalygashkov/streamyx/files/14622545/202403160530_22848.log)

**Comment by IIeTp** [comment]
3.7.3, без `--http2` и `--trace-warnings` просто пустой лог
```
streamyx.exe https://www.crunchyroll.com/ru/series/GY2P9PZPY/tsuredure-children -s 2 -e 8 -d --http2 --trace-warnings
node:internal/util/parse_args/parse_args:101
    throw new ERR_PARSE_ARGS_UNKNOWN_OPTION(shortOrLong, allowPositionals);
    ^

TypeError [ERR_PARSE_ARGS_UNKNOWN_OPTION]: Unknown option '--trace-warnings'. To specify a positional argument starting with a '-', place it at the end of the command after '--', as in '-- "--trace-warnings"
    at new NodeError (node:internal/errors:388:5)
    at checkOptionUsage (node:internal/util/parse_args/parse_args:101:11)
    at parseArgs (node:internal/util/parse_args/parse_args:268:7)
    at getProcessedArgs (C:\snapshot\streamyx\dist\src\args.js:96:44)
    at loadArgs (C:\snapshot\streamyx\dist\src\args.js:172:18)
    at Object.<anonymous> (C:\snapshot\streamyx\dist\src\main.js:50:52)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12) {
  code: 'ERR_PARSE_ARGS_UNKNOWN_OPTION'
}

Node.js v18.5.0
```

**Comment by vitalygashkov** [comment]
> https://www.crunchyroll.com/ru/series/GY2P9PZPY/tsuredure-children -s 2 -e 8

На текущий момент получение метаданных работает через API для мобильных устройств. Так что перед тем, как попытаться скачать - смотрим, есть ли этот эпизод/сезон в мобильном приложении Crunchyroll.

**Comment by IIeTp** [comment]
3.7.4 fixed
